Updated deploy script / removed regex validations.

diff --git a/ecs-deploy b/ecs-deploy
--- a/ecs-deploy
+++ b/ecs-deploy
@@ -114,20 +114,20 @@ echo "Current task definition: $TASK_DEFINITION";
 aws ecs describe-task-definition --task-def $TASK_DEFINITION > def
 
 # Extract the image from its tag
-if ! [[ $IMAGE =~ ^[^:]+:[^:]+$ ]]; then echo "You must specify an image with a tag" && exit 1; fi
+#if ! [[ $IMAGE =~ ^[^:]+:[^:]+$ ]]; then echo "You must specify an image with a tag" && exit 1; fi
 im=`echo $IMAGE | cut -d':' -f 1`
 tag=`echo $IMAGE | cut -d':' -f 2`
 
 # Extract out the repository from the image, if applicable
-if ! [[ $im =~ ^[^/]+/[^/]+$|^[^/]+$ ]]; then echo "Your image/repository specification string is invalid" && exit 1; fi
+#if ! [[ $im =~ ^[^/]+/[^/]+$|^[^/]+$ ]]; then echo "Your image/repository specification string is invalid" && exit 1; fi
 repo=`echo $im | cut -d '/' -f 1`
 imend=`echo $im | cut -d '/' -f 2`
 
 # Replace the image tag in the old def
 if [[ $repo == $imend ]]; then
-  sed -i def -e "s/\(\"image\": \"$repo\)\(:[^ ]\+\)*\"/\1:$tag\"/"
+  sed -i -e "s/\(\"image\": \"$repo\)\(:[^ ]\+\)*\"/\1:$tag\"/" def
 else
-  sed -i def -e "s/\(\"image\": \"$repo\/$imend\)\(:[^ ]\+\)*\"/\1:$tag\"/"
+  sed -i -e "s/\(\"image\": \"$repo\/$imend\)\(:[^ ]\+\)*\"/\1:$tag\"/" def
 fi
 
 # Filter the def
